version: '3.8'
services:
  # local S3
  minio:
    image: minio/minio:RELEASE.2021-08-25T00-41-18Z
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    volumes:
      - storage:/data

volumes:
  storage:
    name: s3